version: '3.8'
services:
  php-apache-environment:
    container_name: php-apachemm
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
      - ./minimum/config/php/php.ini:/usr/local/etc/php/php.ini
    restart: always

  db:
    container_name: dbmm
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_minimum
      MYSQL_USER: user123
      MYSQL_PASSWORD: password123
    ports:
      - "9906:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my-custom.cnf:/etc/mysql/conf.d/my.cnf
    command: --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 15000M
    depends_on:
      - db

  db-backup:
    container_name: db_backup
    build:
      context: ./db-backup
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_minimum
      MYSQL_USER: user123
      MYSQL_PASSWORD: password123
    restart: always

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "443:443"  # เปิดใช้งาน HTTPS
      - "80:80"    # เปิดใช้งาน HTTP
      - "8080:80" # สำหรับ phpMyAdmin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # ไฟล์ config Nginx
      - ./certs:/etc/nginx/certs           # ไฟล์ SSL Certificates
    depends_on:
      - php-apache-environment
    restart: always

volumes:
  db_data:
  backup:
