version: '3.8'
services:
  php-apache-environment:
    container_name: php-apachemm
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80

  db:
    container_name: dbmm
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_minimum
      MYSQL_USER: user123
      MYSQL_PASSWORD: password123
    ports:
      - "9906:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 5000M
    depends_on:
      - db

  db-backup:
    container_name: db_backup
    build:
      context: ./db-backup
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_minimum
      MYSQL_USER: user123
      MYSQL_PASSWORD: password123

volumes:
  db_data:
  backup:
