version: '3.8'
services:
  php-apache-environment:
    container_name: php-apachemm
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
      - ./minimum/config/php/php.ini:/usr/local/etc/php/php.ini
    restart: always

  db:
    container_name: dbmm
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_minimum
      MYSQL_USER: user123
      MYSQL_PASSWORD: password123
    ports:
      - "9906:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my-custom.cnf:/etc/mysql/conf.d/my.cnf
    command: --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80" # Internal HTTP for phpMyAdmin
    restart: always
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 15000M
    depends_on:
      - db

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # phpMyAdmin Redirect
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./path/to/your/local/plugins:/usr/share/nginx/html/plugins

    depends_on:
      - php-apache-environment
      - phpmyadmin
    restart: always

volumes:
  db_data:
